# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EcoPhi
                                 A QGIS plugin
 This plugin performs krigging to produce season cyclicity phase raster maps for a specific time period
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-05
        copyright            : (C) 2026 by Lloyd A. Courtenay (U. Bordeaux)
        email                : ladc1995@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load EcoPhi class from file EcoPhi.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .eco_phi import EcoPhi
    return EcoPhi(iface)
