# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EcoPhiDialog
                                 A QGIS plugin
 This plugin performs krigging to produce season cyclicity phase raster maps for a specific time period
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-05
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Lloyd A. Courtenay (U. Bordeaux)
        email                : ladc1995@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import numpy as np
import pandas as pd
import scipy
from scipy.optimize import curve_fit
from io import StringIO
import geopandas as gpd
from shapely.geometry import Point

import matplotlib.pyplot as plt
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

from osgeo import gdal, osr
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox, QFileDialog
from qgis.core import QgsProject, QgsWkbTypes, QgsMapLayerType, QgsCoordinateReferenceSystem, QgsCoordinateTransform
from qgis.core import QgsRasterLayer

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'eco_phi_dialog_base.ui'))


class EcoPhiDialog(QtWidgets.QDialog, FORM_CLASS):

    def __init__(self, parent=None):
        """Constructor."""
        super(EcoPhiDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        
        self.krigging_model = None
        self.la2004 = None
        self.phi = None
        self.latitude = None
        self.longitude = None
        self.window = None
        self.spacing = 0.25
        self.time = None
        self.activateCalculate = False
        self.pointLayer = None
        self.outputName = None

        self.model_function = None

        self.nodata_value = -9999.0
        self.bins = 15

        self.phi_raster_t = None

        self.distance_matrix = None
        self.sin_phi = None
        self.cos_phi = None
        self.grid_long_mesh = None
        self.grid_lat_mesh = None
        self.grid_extent = None

        self.inside_mask = None
        self.long_flat = None
        self.lat_flat = None
        
        self.setupUi(self)

        self.figure = Figure()
        self.canvas = FigureCanvas(self.figure)
        layout = QtWidgets.QVBoxLayout(self.widgetPlot)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addWidget(self.canvas)

        self.BtnCalculate.setEnabled(False)
        self.tabWidget.setTabEnabled(1, False)
        self.lineEditSolutionsFile.setReadOnly(True)
        self.comboAttribute.setEnabled(False)
        self.spinBoxTime.setEnabled(False)
        self.sliderTime.setEnabled(False)
        self.lineEditsSpacing.setText("0.25")
        self.comboPointLayer.setEnabled(False)

        self.comboWindow.setEnabled(False)
        self.checkRadians.setEnabled(False)
        self.lineEditsSpacing.setReadOnly(True)
        self.lineEditOutputName.setReadOnly(True)
        self.comboKrigging.setEnabled(False)

        self.comboPointLayer.currentIndexChanged.connect(
            self.populate_attributes
        )

        self.comboPointLayer.currentIndexChanged.connect(
            self.getPointData
        )

        self.comboPointLayer.currentIndexChanged.connect(
            self.check_calculate_ability
        )

        self.populate_point_layers()
        self.populate_polygon_layers()

        self.populate_krigging_models()

        self.BtnSelectSolutions.clicked.connect(
            self.select_solutions_file
        )

        self.BtnSelectSolutions.clicked.connect(
            self.check_calculate_ability
        ) 
      
        self.checkRadians.checkStateChanged.connect(
            self.transformPhiData
        )

        self.checkRadians.checkStateChanged.connect(
            self.check_calculate_ability
        )

        self.comboWindow.currentIndexChanged.connect(
            self.createKrigGrid
        )

        self.comboWindow.currentIndexChanged.connect(
            self.activateSpacing
        )

        self.comboWindow.currentIndexChanged.connect(
            self.check_calculate_ability
        )

        self.lineEditsSpacing.editingFinished.connect(
            self.check_numeric
        )

        self.lineEditsSpacing.editingFinished.connect(
            self.createKrigGrid
        )

        self.lineEditsSpacing.editingFinished.connect(
            self.check_calculate_ability
        )

        self.sliderTime.valueChanged.connect(
            self.slider_changed
        )

        self.sliderTime.valueChanged.connect(
            self.check_calculate_ability
        )

        self.spinBoxTime.valueChanged.connect(
            self.spinbox_changed
        )

        self.spinBoxTime.valueChanged.connect(
            self.check_calculate_ability
        )

        self.comboKrigging.currentIndexChanged.connect(
            self.update_krigging_model
        )

        self.comboKrigging.currentIndexChanged.connect(
            self.setKriggingModel
        )

        self.comboKrigging.currentIndexChanged.connect(
            self.check_calculate_ability
        )

        self.comboAttribute.currentIndexChanged.connect(
            self.getPhiData
        )

        self.comboAttribute.currentIndexChanged.connect(
            self.activate_krigging_tab
        )

        self.comboAttribute.currentIndexChanged.connect(
            self.check_calculate_ability
        )

        self.lineEditOutputName.editingFinished.connect(
            self.setName
        )

        self.lineEditOutputName.editingFinished.connect(
            self.check_calculate_ability
        )

        self.BtnCalculate.clicked.connect(
            self.compute
        )

        self.semiVariogramPlotSelect.currentIndexChanged.connect(
            self.update_variogram_plot
        )

        self.radioSin.toggled.connect(self.update_variogram_plot)
        self.radioCos.toggled.connect(self.update_variogram_plot) 
        self.checkIncludeOrbitalPlot.toggled.connect(
            self.update_variogram_plot
        )  

        self.BtnSavePlot.clicked.connect(self.save_plot)

        self.BtnInfo.clicked.connect(self.show_info)
        self.BtnClose.clicked.connect(self.close)

    def check_numeric(self):

        contents = self.lineEditsSpacing.text()

        if "," in contents:
            QMessageBox.warning(
                self,
                "Invalid value",
                "Please use a decimal point (.) rather than a comma (,). "
                "This field can only contain numeric values. "
                "It defines the spacing between points in degrees (latitude and longitude are in degrees) "
                "for the purpose of kriging and creating the final raster map."
            )

            self.lineEditsSpacing.setText("0.25")
            return

        try:

            value = float(contents)

        except ValueError:
            QMessageBox.warning(
                self,
                "Invalid value",
                "This field can only contain numeric values. "
                "It defines the spacing between points in degrees (latitude and longitude are in degrees) "
                "for the purpose of kriging and creating the final raster map."
            )

            self.lineEditsSpacing.setText("0.25")
            return
        
        self.spacing = value

    def save_plot(self):

        filepath, _ = QFileDialog.getSaveFileName(
            self,
            "Save plot",
            "",
            "PNG (*.png);;PDF (*.pdf);;SVG (*.svg);;JPEG (*.jpg *.jpeg)"
        )

        if not filepath:
            return

        self.figure.savefig(
            filepath,
            dpi=500,
            bbox_inches="tight"
        )

    def getPointData(self):

        self.pointLayer = self.comboPointLayer.currentData()

        if not self.pointLayer:
            return

        layer = QgsProject.instance().mapLayer(self.pointLayer)

        if layer is None:
            return

        source_crs = layer.crs()
        target_crs = QgsCoordinateReferenceSystem("EPSG:4326")

        transform = QgsCoordinateTransform(
            source_crs,
            target_crs,
            QgsProject.instance()
        )
        
        self.longitude = []
        self.latitude = []

        for feature in layer.getFeatures():

            point = feature.geometry().asPoint()
            point = transform.transform(point)

            self.longitude.append(point.x())
            self.latitude.append(point.y())

        self.distance_matrix = haversine_distance_matrix(self.longitude, self.latitude)

    def getPhiData(self):

        layer = QgsProject.instance().mapLayer(self.pointLayer)

        if layer is None:
            return

        attribute = self.comboAttribute.currentText()

        if not attribute:
            return
            
        self.phi = []

        for feature in layer.getFeatures():

            value = feature[attribute]

            self.phi.append(value)

        self.sin_phi = np.sin(self.phi)
        self.cos_phi = np.cos(self.phi)

    def transformPhiData(self):

        if self.phi is None:

            return

        if self.checkRadians.isChecked():

            self.phi = np.radians(self.phi)
            self.sin_phi = np.sin(self.phi)
            self.cos_phi = np.cos(self.phi)

    def setName(self):

        self.outputName = self.lineEditOutputName.text()

    def activateSpacing(self):

        self.lineEditsSpacing.setReadOnly(False)

    def createKrigGrid(self):

        layer_id = self.comboWindow.currentData()

        if not layer_id:
            return

        layer = QgsProject.instance().mapLayer(layer_id)

        if layer is None:
            return

        self.window = gpd.GeoDataFrame.from_features(
            layer.getFeatures(),
            crs=layer.crs().authid()
        )

        self.window = self.window.to_crs("EPSG:4326")

        minx, miny, maxx, maxy = self.window.total_bounds
        self.grid_extent = (minx, miny, maxx, maxy)

        krigging_resolution = self.spacing

        grid_long = np.arange(minx, maxx, krigging_resolution)
        grid_lat = np.arange(miny, maxy, krigging_resolution)
        self.grid_long_mesh, self.grid_lat_mesh = np.meshgrid(grid_long, grid_lat)

        self.long_flat = self.grid_long_mesh.ravel()
        self.lat_flat = self.grid_lat_mesh.ravel()

        points = gpd.GeoSeries([Point(x, y) for x, y in zip(self.long_flat, self.lat_flat)], crs="EPSG:4326")
        window_union = self.window.union_all()
        self.inside_mask = points.within(window_union).values

    def activate_krigging_tab(self):

        self.tabWidget.setTabEnabled(1, True)

        self.radioSin.setChecked(True)

        self.update_variogram_plot()

    def calculate_orbital_residuals(self):

        orbital_today = self.la2004[self.la2004["t"] == 0].iloc[0]

        X = build_design_matrix(
            latitude = self.latitude,
            obliquity_rad = orbital_today["obliquity_rad"],
            climatic_precession = (
                orbital_today["eccentricity"] * np.sin(orbital_today["pibar_rad"])
            )
        )

        beta_sin, z_fitted_sin, residuals_sin, r2_sin = fit_trend_ols(
            X, self.sin_phi
        )

        beta_cos, z_fitted_cos, residuals_cos, r2_cos = fit_trend_ols(
            X, self.cos_phi
        )

        return residuals_sin, residuals_cos, r2_sin, r2_cos

    def update_variogram_plot(self):

        if self.sin_phi is None or self.cos_phi is None:

            return

        if self.radioSin.isChecked():

            z = self.sin_phi
            title = r"Empirical Semivariogram - sin($\phi$)"

            if self.checkIncludeOrbitalPlot.isChecked():

                residuals_sin, residuals_cos, r2_sin, r2_cos = (
                    self.calculate_orbital_residuals()
                )
                z = residuals_sin
                title = r"Empirical Semivariogram - residual sin($\phi$)"

        elif self.radioCos.isChecked():

            z = self.cos_phi
            title = r"Empirical Semivariogram - cos($\phi$)"

            if self.checkIncludeOrbitalPlot.isChecked():

                residuals_sin, residuals_cos, r2_sin, r2_cos = (
                    self.calculate_orbital_residuals()
                )
                z = residuals_cos
                title = r"Empirical Semivariogram - residual cos($\phi$)"

        else:
            return

        lag_centers, gamma_hat, n_pairs = empirical_variogram(
            self.distance_matrix,
            z,
            n_bins = self.bins
        )

        nugget, sill, vario_range = calculate_variogram_parameters(
            lag_centers, gamma_hat, n_pairs
        )

        self.labelNugget.setText(f"Nugget: {nugget:.3f}")
        self.labelSill.setText(f"Sill: {sill:.3f}")
        self.labelRange.setText(f"Range: {vario_range:.1f} Km")

        self.labelR2.setText(
            f"R2: 0"
        )

        self.labelRMSE.setText(
            f"RMSE: 0"
        )

        model_func = self.get_variogram_plot_model()

        popt = None

        if model_func is not None:

            popt, pcov = fit_variogram_model(
                model_func,
                lag_centers,
                gamma_hat,
                n_pairs
            )

            nugget, sill, vario_range = popt

            self.labelNugget.setText(
                f"Nugget: {nugget:.3f}"
            )

            self.labelSill.setText(
                f"Sill: {sill:.3f}"
            )

            self.labelRange.setText(
                f"Range: {vario_range:.1f} Km"
            )

            variogram_rmse, _, variogram_r2 = variogram_residuals_r2(model_func, popt, lag_centers, gamma_hat, n_pairs)
            variogram_rmse = np.sqrt(np.mean(variogram_rmse**2))

            self.labelR2.setText(
                f"R2: {variogram_r2:.3f}"
            )

            self.labelRMSE.setText(
                f"RMSE: {variogram_rmse:.3f}"
            )

        self.plot_variogram(
            lag_centers,
            gamma_hat,
            n_pairs,
            model_func = model_func,
            popt = popt,
            title = title
        )

    def plot_variogram(
        self, lag_centers,
        gamma_hat, n_pairs,
        model_func = None,
        popt = None,
        title="Empirical Semivariogram"
    ):
        
        self.figure.clear()
        ax = self.figure.add_subplot(111)

        valid = (
            (n_pairs > 0) &
            np.isfinite(gamma_hat)
        )

        ax.scatter(
            lag_centers[valid],
            gamma_hat[valid],
            s=100,
            edgecolor="k",
            alpha=0.7
        )

        if model_func is not None and popt is not None:

            h_smooth = np.linspace(
                0,
                lag_centers[valid].max(),
                200
            )

            ax.plot(
                h_smooth,
                model_func(h_smooth, *popt),
                linewidth=2,
                c = "red",
                label="Fitted model"
            )

            ax.legend()

        ax.set_ylabel(r"$\hat{\gamma}(h)$")
        ax.set_xlabel(r"$h$")
        ax.set_title(title)

        ax.set_ylim(
            0,
            np.nanmax(gamma_hat) + np.nanstd(gamma_hat)
        )

        ax.grid(alpha=0.3)

        self.figure.tight_layout()

        self.canvas.draw()
    
    def populate_point_layers(self):

        self.comboPointLayer.clear()

        layers = QgsProject.instance().mapLayers().values()

        for layer in layers:

            if layer.type() != QgsMapLayerType.Vector:
                continue
            
            geometry_type = QgsWkbTypes.geometryType(layer.wkbType())

            if geometry_type == QgsWkbTypes.PointGeometry:

                self.comboPointLayer.addItem(
                    layer.name(),
                    layer.id()
                )

    def populate_polygon_layers(self):

        self.comboWindow.clear()

        layers = QgsProject.instance().mapLayers().values()

        for layer in layers:

            if layer.type() != QgsMapLayerType.Vector:

                continue

            geometry_type = QgsWkbTypes.geometryType(layer.wkbType())

            if geometry_type == QgsWkbTypes.PolygonGeometry:

                self.comboWindow.addItem(
                    layer.name(),
                    layer.id()
                )
    
    def populate_attributes(self):

        self.comboAttribute.setEnabled(True)
        self.comboAttribute.clear()

        layer_id = self.comboPointLayer.currentData()

        if not layer_id:
            return

        layer = QgsProject.instance().mapLayer(layer_id)

        if layer is None:
            return

        for field in layer.fields():

            self.comboAttribute.addItem(field.name())

    def select_solutions_file(self):

        filepath, _ = QFileDialog.getOpenFileName(
            self,
            "Select LA2004 solutions file",
            "",
            "Text files (*.txt);;All files (*)"
        )

        if not filepath:
            return

        self.la2004 = load_la2004(filepath)

        self.configure_time_controls()
        self.update_time_controls()

        self.lineEditSolutionsFile.setText(filepath)
        self.comboPointLayer.setEnabled(True)
        self.comboWindow.setEnabled(True)
        self.checkRadians.setEnabled(True)
        self.lineEditOutputName.setReadOnly(False)
        self.comboKrigging.setEnabled(True)

        self.check_calculate_ability()

    def configure_time_controls(self):

        t_min = int(self.la2004["t"].min())
        t_max = int(self.la2004["t"].max())

        self.sliderTime.setMinimum(t_min)
        self.sliderTime.setMaximum(t_max)

        self.spinBoxTime.setMinimum(t_min)
        self.spinBoxTime.setMaximum(t_max)

        self.sliderTime.setValue(t_max)
        self.spinBoxTime.setValue(t_max)

        self.time = t_max

    def slider_changed(self, value):

        value = int(value)

        self.spinBoxTime.setValue(value)
        self.time = value

    def spinbox_changed(self, value):

        value = int(value)

        self.sliderTime.setValue(value)
        self.time = value

    def populate_krigging_models(self):

        self.comboKrigging.clear()

        self.comboKrigging.addItem("Select kriging model...")
        self.comboKrigging.addItems([
            "Exponential",
            "Gaussian",
            "Spherical"
        ])

        self.comboKrigging.setCurrentIndex(0)

        self.semiVariogramPlotSelect.clear()

        self.semiVariogramPlotSelect.addItem("Select kriging model...")
        self.semiVariogramPlotSelect.addItems([
            "None",
            "Exponential",
            "Gaussian",
            "Spherical"
        ])

        self.semiVariogramPlotSelect.setCurrentIndex(0)

    def update_krigging_model(self):

        model = self.comboKrigging.currentText()

        if model == "Exponential":

            self.krigging_model = "exp"

        elif model == "Gaussian":

            self.krigging_model = "gau"

        elif model == "Spherical":

            self.krigging_model = "sph"

        else:

            self.krigging_model = None

        self.update_time_controls()

    def setKriggingModel(self):

        if self.krigging_model == "exp":

            def target_model(h, nugget, sill, emp_range):

                partial_sill = sill - nugget
                gamma = nugget + partial_sill * (1 - np.exp(-h / emp_range))
                gamma = np.where(h == 0, 0, gamma)

                return gamma

            self.model_function = target_model
        
        elif self.krigging_model == "gau":

            def target_model(h, nugget, sill, emp_range):

                partial_sill = sill - nugget
                gamma = nugget + partial_sill * (1 - np.exp(-(h**2) / (emp_range**2)))
                gamma = np.where(h == 0, 0, gamma)

                return gamma
            
            self.model_function = target_model

        elif self.krigging_model == "sph":

            def target_model(h, nugget, sill, emp_range):

                partial_sill = sill - nugget
                gamma = np.where(
                    h <= emp_range,
                    nugget + partial_sill * (1.5 * (h / emp_range) - 0.5 * (h / emp_range)**3),
                    sill
                )

                gamma = np.where(h == 0, 0, gamma)

                return gamma
            
            self.model_function = target_model

    def get_variogram_plot_model(self):

        model = self.semiVariogramPlotSelect.currentText()

        if model == "Exponential":

            def target_model(h, nugget, sill, emp_range):

                partial_sill = sill - nugget
                gamma = nugget + partial_sill * (1 - np.exp(-h / emp_range))
                gamma = np.where(h == 0, 0, gamma)

                return gamma

            return target_model
        
        elif model == "Gaussian":

            def target_model(h, nugget, sill, emp_range):

                partial_sill = sill - nugget
                gamma = nugget + partial_sill * (1 - np.exp(-(h**2) / (emp_range**2)))
                gamma = np.where(h == 0, 0, gamma)

                return gamma
            
            return target_model

        elif model == "Spherical":

            def target_model(h, nugget, sill, emp_range):

                partial_sill = sill - nugget
                gamma = np.where(
                    h <= emp_range,
                    nugget + partial_sill * (1.5 * (h / emp_range) - 0.5 * (h / emp_range)**3),
                    sill
                )

                gamma = np.where(h == 0, 0, gamma)

                return gamma
            
            return target_model
        
        else:

            return None

    def update_time_controls(self):

        model_selected = self.krigging_model is not None
        solutions_loaded = self.la2004 is not None

        enabled = model_selected and solutions_loaded

        self.spinBoxTime.setEnabled(enabled)
        self.sliderTime.setEnabled(enabled)

    def check_calculate_ability(self):

        inputs = [
            self.krigging_model,
            self.la2004,
            self.phi,
            self.latitude,
            self.longitude,
            self.window,
            self.spacing,
            self.time,
            self.pointLayer,
            self.outputName
        ]

        self.activateCalculate = all(
            value is not None for value in inputs
        )

        self.BtnCalculate.setEnabled(
            self.activateCalculate
        )

    def compute(self):

        self.perform_predictions()
        self.createRaster()

    def createRaster(self):

        rows, cols = self.phi_raster_t.shape
        minx, miny, maxx, maxy = self.grid_extent
        pixel_width = self.spacing
        pixel_height = self.spacing

        filepath, _ = QFileDialog.getSaveFileName(
            self,
            "Save raster",
            f"{self.outputName}.tif",
            "GeoTiff (*.tif)"
        )

        if not filepath:
            return

        driver = gdal.GetDriverByName("GTiff")

        dataset = driver.Create(
            filepath,
            cols,
            rows,
            1,
            gdal.GDT_Float32,
            options = ["COMPRESS=LZW"]
        )

        if dataset is None:

            QMessageBox.critical(
                self,
                "Raster creation failed",
                "Could not create the output raster."
            )

            return

        dataset.SetGeoTransform(
            (
                minx,
                pixel_width,
                0,
                maxy,
                0,
                -pixel_height
            )
        )

        spatial_reference = osr.SpatialReference()
        spatial_reference.ImportFromEPSG(4326)
        dataset.SetProjection(
            spatial_reference.ExportToWkt()
        )

        band = dataset.GetRasterBand(1)
        band.WriteArray(self.phi_raster_t)

        band.SetNoDataValue(self.nodata_value)

        band.FlushCache()
        dataset.FlushCache()
        dataset = None

        raster_layer = QgsRasterLayer(
            filepath,
            self.outputName
        )

        if not raster_layer.isValid():

            QMessageBox.critical(
                self,
                "Raster loading failed",
                "The raster was created but could not be loaded into QGIS."
            )

            return
        
        QgsProject.instance().addMapLayer(raster_layer)

        QMessageBox.information(
            self,
            "EcoPhi — Calculation Complete",
            f"The EcoPhi calculation was completed successfully.\n\n"
            f"Raster: {self.outputName}\n\n"
            f"Reminder: phi is a circular variable. Therefore, if you wish to "
            f"create visually accurate maps, a cyclic colour palette is required."
        )

    def perform_predictions(self):
        
        orbital_today = self.la2004[self.la2004["t"] == 0].iloc[0]

        long_inside = self.long_flat[self.inside_mask]
        lat_inside = self.lat_flat[self.inside_mask]
        lat_inside_rad = np.radians(lat_inside)

        X = build_design_matrix(
            latitude = self.latitude,
            obliquity_rad = orbital_today["obliquity_rad"],
            climatic_precession = orbital_today["eccentricity"] * np.sin(orbital_today["pibar_rad"])
        )

        beta_sin, z_fitted_sin, residuals_sin, r2_sin = fit_trend_ols(X, self.sin_phi)
        X_cos = X
        beta_cos, z_fitted_cos, residuals_cos, r2_cos = fit_trend_ols(X_cos, self.cos_phi)

        lag_centers_r, gamma_hat_r, n_pairs_r = empirical_variogram(
            self.distance_matrix, residuals_sin, n_bins = self.bins
        )

        lag_centers_rcos, gamma_hat_rcos, n_pairs_rcos = empirical_variogram(
            self.distance_matrix, residuals_cos, n_bins = self.bins
        )

        model_params_resid, model_pcov_resid = fit_variogram_model(
            self.model_function, lag_centers_r, gamma_hat_r, n_pairs_r
        )

        model_params_resid_cos, exp_pcov_resid_cos = fit_variogram_model(
            self.model_function, lag_centers_rcos, gamma_hat_rcos, n_pairs_rcos
        )

        Gamma_sin = build_gamma_matrix(
            self.distance_matrix, self.model_function, model_params_resid
        )
        A_sin = build_krigging_system(Gamma_sin)
        A_inv_sin = np.linalg.inv(A_sin)

        Gamma_cos = build_gamma_matrix(
            self.distance_matrix, self.model_function, model_params_resid_cos
        )
        A_cos = build_krigging_system(Gamma_cos)
        A_inv_cos = np.linalg.inv(A_cos)

        resid_sin_pred, resid_sin_var = krige_grid(
            long_inside, lat_inside,
            self.longitude, self.latitude,
            residuals_sin,
            self.model_function, model_params_resid, A_inv_sin
        )

        resid_cos_pred, resid_cos_var = krige_grid(
            long_inside, lat_inside,
            self.longitude, self.latitude,
            residuals_cos,
            self.model_function, model_params_resid_cos, A_inv_cos
        )

        obliquity_t = np.interp(self.time, self.la2004["t"].values[::-1], self.la2004["obliquity_rad"].values[::-1])
        ecc_t = np.interp(self.time, self.la2004["t"].values[::-1], self.la2004["eccentricity"].values[::-1])
        pibar_t = np.interp(self.time, self.la2004["t"].values[::-1], self.la2004["pibar_rad"].values[::-1])
        precession_t = ecc_t * np.sin(pibar_t)

        trend_sin_t = (beta_sin[0] +
                        beta_sin[1] * precession_t * np.sin(lat_inside_rad) +
                        beta_sin[2] * obliquity_t * np.abs(lat_inside_rad))

        trend_cos_t = (beta_cos[0] +
                        beta_cos[1] * precession_t * np.sin(lat_inside_rad) +
                        beta_cos[2] * obliquity_t * np.abs(lat_inside_rad))

        sin_pred_t = trend_sin_t + resid_sin_pred
        cos_pred_t = trend_cos_t + resid_cos_pred

        phi_pred_t = np.mod(np.arctan2(sin_pred_t, cos_pred_t), 2 * np.pi)
        self.phi_raster_t = reassemble_raster(
            phi_pred_t,
            self.inside_mask,
            self.grid_long_mesh.shape,
            self.nodata_value
        )

    def show_info(self):

        QMessageBox.information(
            self,
            "EcoPhi — Information",
            "xxx"
        )

def load_la2004(filepath):

    with open(filepath, "r") as f:
        lines = f.readlines()
    
    cleaned_lines = [line.replace("D+", "E+").replace("D-", "E-") for line in lines]
    
    data_str = "".join(cleaned_lines)
    
    df = pd.read_csv(
        StringIO(data_str),
        sep=r"\s+",
        header=None,
        names=["t", "eccentricity", "obliquity_rad", "pibar_rad"]
    )
    
    df["obliquity_deg"] = np.degrees(df["obliquity_rad"])
    df["climatic_precession"] = df["eccentricity"] * np.sin(df["pibar_rad"])
    
    return df

def haversine_distance_matrix(lon, lat):

    # radius of the earh in km
    
    R = 6371.0

    lon_rad = np.radians(lon)
    lat_rad = np.radians(lat)

    dlat = lat_rad[:, None] - lat_rad[None, :]
    dlon = lon_rad[:, None] - lon_rad[None, :]

    a = (
        np.sin(dlat / 2)**2 + np.cos(lat_rad[:, None]) * np.cos(lat_rad[None, :]) * np.sin(dlon / 2)**2
    )
    c = 2 * np.arcsin(np.sqrt(a))

    return(R * c)

def empirical_variogram(dist_matrix, z, n_bins = 15, max_lag = None):

    n = len(z)

    iu, ju = np.triu_indices(n, k = 1)

    h_values = dist_matrix[iu, ju]
    square_difference = (z[iu] - z[ju])**2

    if max_lag is None:
        
        max_lag = h_values.max() / 2

    bin_edges = np.linspace(0, max_lag, n_bins + 1)
    bin_index = np.digitize(h_values, bin_edges) - 1

    lag_centers = np.zeros(n_bins)
    gamma_hat = np.full(n_bins, np.nan)
    n_pairs = np.zeros(n_bins, dtype = int)

    for target_bin in range(n_bins):

        mask = bin_index == target_bin
        n_pairs[target_bin] = mask.sum()
        lag_centers[target_bin] = 0.5 * (bin_edges[target_bin] + bin_edges[target_bin + 1])

        if n_pairs[target_bin] > 0:

            gamma_hat[target_bin] = 0.5 * np.mean(square_difference[mask])

    return lag_centers, gamma_hat, n_pairs

def calculate_variogram_parameters(lag_centers, gamma_hat, n_pairs):

    valid = (
        (n_pairs > 0) &
        np.isfinite(gamma_hat)
    )

    lags = lag_centers[valid]
    gamma = gamma_hat[valid]

    nugget = gamma[0]
    sill = np.max(gamma)
    vario_range = lags[np.argmax(gamma)]

    return nugget, sill, vario_range

def exponential_model(h, nugget, sill, emp_range):

    partial_sill = sill - nugget
    gamma = nugget + partial_sill * (1 - np.exp(-h / emp_range))
    gamma = np.where(h == 0, 0, gamma)

    return gamma

def spherical_model(h, nugget, sill, emp_range):

    partial_sill = sill - nugget
    gamma = np.where(
        h <= emp_range,
        nugget + partial_sill * (1.5 * (h / emp_range) - 0.5 * (h / emp_range)**3),
        sill
    )

    gamma = np.where(h == 0, 0, gamma)

    return gamma

def gaussian_model(h, nugget, sill, emp_range):

    partial_sill = sill - nugget
    gamma = nugget + partial_sill * (1 - np.exp(-(h**2) / (emp_range**2)))
    gamma = np.where(h == 0, 0, gamma)

    return gamma

def fit_variogram_model(model_func, lag_centers, gamma_hat, n_pairs, p0 = None, weighted = True):

    valid = n_pairs > 0 # remove any invalid bins based on pairs
    h = lag_centers[valid]
    g = gamma_hat[valid]
    w = n_pairs[valid]

    if p0 is None:

        nugget0 = g[0] if len(g) > 0 else 0.0
        sill0 = np.nanmax(g)
        range0 = h[np.nanargmax(g)] if np.nanargmax(g) > 0 else h.max() / 2
        p0 = [nugget0, sill0, range0]

    bounds = ([0, 0, 1e-6], [np.inf, np.inf, np.inf])

    if weighted:
        sigma = 1 / np.sqrt(w)
    else:
        sigma = None

    popt, pcov = curve_fit(
        model_func, h, g, p0 = p0, bounds = bounds,
        sigma = sigma, absolute_sigma = False, maxfev = 10000
    )

    return popt, pcov

def plot_variogram_curve(lag_centers, gamma_hat, n_pairs,
                          model_func, popt,
                          title="Curve"):
    plt.figure(figsize=(8, 4))
    
    plt.scatter(lag_centers, gamma_hat, s=100, edgecolor='k', alpha=0.7)
    h_smooth = np.linspace(0.01, lag_centers.max(), 200)
    plt.plot(h_smooth, model_func(h_smooth, *popt), linewidth = 2, c = "red")
    
    plt.ylabel(r'$\hat{\gamma}(h)$')
    plt.xlabel(r'$h$')
    plt.title(title)
    plt.ylim(0, np.max(gamma_hat) + np.std(gamma_hat))
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()

def variogram_residuals_r2(model_function, popt, lag_centers, gamma_hat, n_pairs):
    
    valid = n_pairs > 0
    h = lag_centers[valid]
    g_obs = gamma_hat[valid]
    w = n_pairs[valid]
    
    g_pred = model_function(h, *popt)
    residuals = g_obs - g_pred
    
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((g_obs - np.mean(g_obs))**2)
    r2 = 1 - ss_res / ss_tot
    
    weighted_mean = np.average(g_obs, weights=w)
    ss_res_w = np.sum(w * residuals**2)
    ss_tot_w = np.sum(w * (g_obs - weighted_mean)**2)
    weighted_r2 = 1 - ss_res_w / ss_tot_w
    
    return residuals, r2, weighted_r2

def build_gamma_matrix(dist_matrix, model_function, popt):

    Gamma = model_function(dist_matrix, *popt)
    np.fill_diagonal(Gamma, 0)
    return Gamma

def build_krigging_system(Gamma):

    n = Gamma.shape[0]
    A = np.zeros((n + 1, n + 1))
    A[:n, :n] = Gamma
    A[:n, n] = 1
    A[n, :n] = 1
    A[n, n] = 0

    return A

def ordinary_kriging_predict(sX_long, sX_lat, sample_long, sample_lat, z,
                            model_function, popt, A_inv = None, A = None):

    n = len(z)

    long_rad_0, lat_rad_0 = np.radians(sX_long), np.radians(sX_lat)
    long_rad_s, lat_rad_s = np.radians(sample_long), np.radians(sample_lat)

    dlat = lat_rad_s - lat_rad_0
    dlong = long_rad_s - long_rad_0

    a = np.sin(dlat / 2)**2 + np.cos(lat_rad_0) * np.cos(lat_rad_s) * np.sin(dlong / 2)**2
    h0 = 6371.0 * 2 * np.arcsin(np.sqrt(a))

    gamma_0 = model_function(h0, *popt)

    rhs = np.append(gamma_0, 1)

    if A_inv is not None:

        weights_m = A_inv @ rhs

    else:

        weights_m = np.linalg.solve(A, rhs)

    lamda_value = weights_m[:n]
    m = weights_m[n]

    z_pred = np.sum(lambda_value * z)
    kriging_variance = np.sum(lambda_value * gamma_0) + m

    return z_pred, kriging_variance

def krige_grid(long_pred, lat_pred, sample_long, sample_lat, z, model_function, popt, A_inv):

    n = len(z)
    m = len(long_pred)
    z_pred = np.full(m, np.nan)
    krig_var = np.full(m, np.nan)

    long_rad_s = np.radians(sample_long)
    lat_rad_s = np.radians(sample_lat)
    R = 6371.0

    for i in range(m):
        
        long_rad_0 = np.radians(long_pred[i])
        lat_rad_0 = np.radians(lat_pred[i])

        dlat = lat_rad_s - lat_rad_0
        dlong = long_rad_s - long_rad_0
        a = np.sin(dlat / 2)**2 + np.cos(lat_rad_0) * np.cos(lat_rad_s) * np.sin(dlong / 2)**2
        h0 = R * 2 * np.arcsin(np.sqrt(a))

        gamma_0 = model_function(h0, *popt)
        rhs = np.append(gamma_0, 1)
        weights_m = A_inv @ rhs

        lam = weights_m[:n]
        mlag = weights_m[n]

        z_pred[i] = np.sum(lam * z)
        krig_var[i] = np.sum(lam * gamma_0) + mlag

        #if i % 500 == 0:
        #    print(f"  {i}/{m} predicted...")

    return z_pred, krig_var

def build_design_matrix(latitude, obliquity_rad, climatic_precession):
    
    lat_rad = np.radians(latitude)
    n = len(latitude)

    obl_arr = np.full(n, obliquity_rad) if np.isscalar(obliquity_rad) else obliquity_rad
    prec_arr = np.full(n, climatic_precession) if np.isscalar(climatic_precession) else climatic_precession

    intercept = np.ones(n)
    prec_lat_interaction = prec_arr * np.sin(lat_rad)
    obl_lat_interaction = obl_arr * np.abs(lat_rad)

    X = np.column_stack([intercept, prec_lat_interaction, obl_lat_interaction])
    
    return X

def fit_trend_ols(X, z):


    beta, residuals_ss, rank, singular_values = np.linalg.lstsq(X, z, rcond = None)

    z_fitted = X @ beta
    residuals = z - z_fitted

    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((z - np.mean(z))**2)
    r2 = 1 - ss_res / ss_tot

    return beta, z_fitted, residuals, r2

def reassemble_raster(values_inside, inside_mask, grid_shape, nodata_value):
    
    full = np.full(inside_mask.shape, nodata_value)
    full[inside_mask] = values_inside
    raster = full.reshape(grid_shape)
    raster = np.flipud(raster)
    return raster
